# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8123b123a8703dd2b78050094e719dbc6f8e271f74802be3fd1a08a84f25747b0e9fc5dfb79a0abe711dcb0d53b9c26b7f3108e9e65f16ed3f4dbc094cae84fc

test:
  secret_key_base: 1e469998b06d39e314204b4090d39139cdfd36a8fa903db153950501d512a0bf7bcca0916cb4b46ec5f8d03aa9b4f2202a1391c00c18580d3255c8083944a57b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
